export default [
  {
    code: 1000,
    day: "Soleado",
    night: "Despejado",
    icon: 113,
  },
  {
    code: 1003,
    day: "Parcialmente nublado",
    night: "Parcialmente nublado",
    icon: 116,
  },
  {
    code: 1006,
    day: "Nublado",
    night: "Nublado",
    icon: 119,
  },
  {
    code: 1009,
    day: "Nublado Completo",
    night: "Nublado Completo",
    icon: 122,
  },
  {
    code: 1030,
    day: "Neblinoso",
    night: "Neblinoso",
    icon: 143,
  },
  {
    code: 1063,
    day: "Posible lluvia dispersa",
    night: "Posible lluvia dispersa",
    icon: 176,
  },
  {
    code: 1066,
    day: "Posible nieve dispersa",
    night: "Posible nieve dispersa",
    icon: 179,
  },
  {
    code: 1069,
    day: "Posible aguanieve dispersa",
    night: "Posible aguanieve dispersa",
    icon: 182,
  },
  {
    code: 1072,
    day: "Posible llovizna helada dispersa",
    night: "Posible llovizna helada dispersa",
    icon: 185,
  },
  {
    code: 1087,
    day: "Posibles brotes de truenos",
    night: "Posibles brotes de truenos",
    icon: 200,
  },
  {
    code: 1114,
    day: "Ventisca",
    night: "Ventisca",
    icon: 227,
  },
  {
    code: 1117,
    day: "Tormenta de nieve",
    night: "Tormenta de nieve",
    icon: 230,
  },
  {
    code: 1135,
    day: "Neblina",
    night: "Neblina",
    icon: 248,
  },
  {
    code: 1147,
    day: "Neblina fría",
    night: "Neblina fría",
    icon: 260,
  },
  {
    code: 1150,
    day: "Llovizna ligera dispersa",
    night: "Llovizna ligera dispersa",
    icon: 263,
  },
  {
    code: 1153,
    day: "Llovizna ligera",
    night: "Llovizna ligera",
    icon: 266,
  },
  {
    code: 1168,
    day: "Llovizna helada",
    night: "Llovizna helada",
    icon: 281,
  },
  {
    code: 1171,
    day: "Fuerte Llovizna helada",
    night: "Fuerte Llovizna helada",
    icon: 284,
  },
  {
    code: 1180,
    day: "Lluvia ligera dispersa",
    night: "Lluvia ligera dispersa",
    icon: 293,
  },
  {
    code: 1183,
    day: "Lluvia ligera",
    night: "Lluvia ligera",
    icon: 296,
  },
  {
    code: 1186,
    day: "Lluvia moderada ocasional",
    night: "Lluvia moderada ocasional",
    icon: 299,
  },
  {
    code: 1189,
    day: "Lluvia moderada",
    night: "Lluvia moderada",
    icon: 302,
  },
  {
    code: 1192,
    day: "Lluvia intensa ocasional",
    night: "Lluvia intensa ocasional",
    icon: 305,
  },
  {
    code: 1195,
    day: "Lluvia fuerte",
    night: "Lluvia fuerte",
    icon: 308,
  },
  {
    code: 1198,
    day: "Lluvia congelada ligera",
    night: "Lluvia congelada ligera",
    icon: 311,
  },
  {
    code: 1201,
    day: "Lluvia moderada/fuerte congelada",
    night: "Lluvia moderada/fuerte congelada",
    icon: 314,
  },
  {
    code: 1204,
    day: "Aguanieve ligera",
    night: "Aguanieve ligera",
    icon: 317,
  },
  {
    code: 1207,
    day: "Aguanieve moderada o fuerte",
    night: "Aguanieve moderada o fuerte",
    icon: 320,
  },
  {
    code: 1210,
    day: "Nieve ligera y dispersa",
    night: "Nieve ligera y dispersa",
    icon: 323,
  },
  {
    code: 1213,
    day: "Nieve ligera",
    night: "Nieve ligera",
    icon: 326,
  },
  {
    code: 1216,
    day: "Nieve moderada dispersa",
    night: "Nieve moderada dispersa",
    icon: 329,
  },
  {
    code: 1219,
    day: "Nieve moderada",
    night: "Nieve moderada",
    icon: 332,
  },
  {
    code: 1222,
    day: "Nieve fuerte dispersa",
    night: "Nieve fuerte dispersa",
    icon: 335,
  },
  {
    code: 1225,
    day: "Fuertes nieves",
    night: "Fuertes nieves",
    icon: 338,
  },
  {
    code: 1237,
    day: "Pellets de hielo",
    night: "Pellets de hielo",
    icon: 350,
  },
  {
    code: 1240,
    day: "Lluvia ligera",
    night: "Lluvia ligera",
    icon: 353,
  },
  {
    code: 1243,
    day: "Lluvia moderada o fuerte",
    night: "Lluvia moderada o fuerte",
    icon: 356,
  },
  {
    code: 1246,
    day: "Lluvia torrencial",
    night: "Lluvia torrencial",
    icon: 359,
  },
  {
    code: 1249,
    day: "Aguanieve ligera",
    night: "Aguanieve ligera",
    icon: 362,
  },
  {
    code: 1252,
    day: "Aguanieve moderada o fuerte",
    night: "Aguanieve moderada o fuerte",
    icon: 365,
  },
  {
    code: 1255,
    day: "Nieve ligera",
    night: "Nieve ligera",
    icon: 368,
  },
  {
    code: 1258,
    day: "Nieves fuertes/moderadas",
    night: "Nieves fuertes/moderadas",
    icon: 371,
  },
  {
    code: 1261,
    day: "Ligeras lluvias de Pellets de hielo",
    night: "Ligeras lluvias de Pellets de hielo",
    icon: 374,
  },
  {
    code: 1264,
    day: "Lluvia moderada/fuerte de Pellets de hielo",
    night: "Lluvia moderada/fuerte de Pellets de hielo",
    icon: 377,
  },
  {
    code: 1273,
    day: "Lluvia ligera dispersa con truenos",
    night: "Lluvia ligera dispersa con truenos",
    icon: 386,
  },
  {
    code: 1276,
    day: "Lluvia moderada/fuerte con truenos",
    night: "Lluvia moderada/fuerte con truenos",
    icon: 389,
  },
  {
    code: 1279,
    day: "Nieve ligera y dispersa con truenos",
    night: "Nieve ligera y dispersa con truenos",
    icon: 392,
  },
  {
    code: 1282,
    day: "Moderate or Fuertes nieves con truenos",
    night: "Moderate or Fuertes nieves con truenos",
    icon: 395,
  },
];
